// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UserManagement.Models
{
    public partial class GetSingleUserDetailsResult
    {
        public int UserId { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Designation is required.")]
        public string UserDesignation { get; set; }
        [Required(ErrorMessage = "City is required.")]
        public string UserCity { get; set; }
        public bool? UserIsActive { get; set; }
    }
}
