// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using UserManagement.Models;

namespace UserManagement.Models
{
    public partial interface IUserContextProcedures
    {
        Task<List<AddUserDetailsResult>> AddUserDetailsAsync(string Name, string Designation, string City, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AddUserSkillAsync(int? UserId, int? SkillId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllSkillsResult>> GetAllSkillsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllUsersDetailsResult>> GetAllUsersDetailsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllUsersSkillsResult>> GetAllUsersSkillsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllUsersWithSkillsResult>> GetAllUsersWithSkillsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetDeletedRecordsResult>> GetDeletedRecordsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetEmployeeWithSkillsResult>> GetEmployeeWithSkillsAsync(int? UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetSingleUserDetailsResult>> GetSingleUserDetailsAsync(int? UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> InsertEmployeeWithSkillsAsync(string UserName, string Designation, string City, string SkillIds, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> RestoreEmployeeAsync(int? Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SoftDeleteUserAsync(int? UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateUserWithSkillsAsync(int? UserId, string UserName, string Designation, string City, string NewSkillIds, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
