// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using UserManagement.Models;

namespace UserManagement.Models
{
    public partial interface IUserContextProcedures
    {
        Task<int> CreateUserAsync(string Name, string Designation, int? Age, string City, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DeletedUsersResult>> DeletedUsersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteUserAsync(int? Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllUsersResult>> GetAllUsersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<GetUserByIdResult> GetUserByIdAsync(int? Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> RestoreUserAsync(int? Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateUserAsync(int? Id, string Name, string Designation, int? Age, string City, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
