// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UserManagement.Models;

public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Designation { get; set; }

    public string City { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Skill> Skills { get; set; } = new List<Skill>();
}